# from the main project folder run:
# quarto render tutorial

project:
  type: website
  render:
    - "*.qmd"
  output-dir: ../../ts-feature-clustering-illustration
  resources:
    - CNAME

website:
  page-navigation: true
  title: "Tutorial: Feature Based Time Series Clustering in Psychology"
  description: "Short description goes here."
  site-url: "https://www.tsfeatureclustr.com/" 
  repo-url: "https://github.com/JannisCodes/migration-trajectories"
  open-graph: true
  
  favicon: "images/android-chrome-192x192.png"

  twitter-card:
    creator: "@JannisWrites"
    image: "images/twitter-card.png"
  
  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    
    tools: 
      - icon: database-fill
        href: https://doi.org/10.17605/OSF.IO/J8DZV
        text: OSF Repository
      - icon: github
        text: Project Repository
        href: https://github.com/JannisCodes/migration-trajectories
      
    
    contents:
      - href: index.qmd
        text: Welcome
      - href: 01-input-variables.qmd
        text: 1. Input Variables
      - href: 02-feature-extraction.qmd
        text: 2. Feature Extraction
      - href: 03-feature-reduction.qmd
        text: 3. Feature Reduction
      - href: 04-clustering.qmd
        text: 4. Clustering
      - href: 05-evaluation.qmd
        text: 5. Evaluation
      - href: 06-validation-analyses.qmd
        text: 6. Validation Analyses
      - href: about.qmd
        text: About

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    highlight-style: pygments
    # code-line-numbers: true
    # code-tools: true
    code-copy: true
    code-overflow: wrap
    toc: true
    css: styles.css

freeze: auto

editor: visual

